### ISSUE TITLE
dotnet publish

### ISSUE THREAD

**Issue by FalkWinkler** [CZEMacLeod/MSBuild.SDK.SystemWeb#20]
How can use the dotnet publish command?

**Comment by CZEMacLeod** [comment]
@FalkWinkler This SDK [does not support the dotnet command](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/issues/1) (other than for creating a new project using the template) as it is all NETFramework based. You can use MSBuild to build and publish your project.

```cmd
msbuild /t:Publish /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingeFile=true /p:PackageLocation="MyPublishDir"
```
or
```cmd
msbuild "path\to\your\solution.sln" /t:rebuild ^
				    /p:Configuration=Release ^
				    /p:DeployOnBuild=True ^
				    /p:DeployDefaultTarget=WebPublish ^
				    /p:WebPublishMethod=FileSystem ^
				    /p:DeleteExistingFiles=True ^
				    /p:publishUrl="path\to\your\output\folder"
```
These properties are documented for MSBuild and Publishing Profiles for ASP.NET 4 WebApplication projects.
