### ISSUE TITLE
.aspx and .asax files don't get published

### ISSUE THREAD

**Issue by chucker** [CZEMacLeod/MSBuild.SDK.SystemWeb#24]
I'm deploying as follows:

    msbuild /t:Restore,Rebuild /p:DeployOnBuild=true /p:PublishProfile=Live.pubxml
    /p:Password="(my password)" /p:Configuration=Live .\MyProject\MyProject.csproj

This _does_ build a new DLL and upload that and its dependencies to the server. However, it does not replace any `aspx` files on the server.

I notice VS infers the build action for `aspx` as `None`, and I'm not seeing a reason at a glance, in my `csproj`. Some snippets:

```xml
<Project Sdk="MSBuild.SDK.SystemWeb/4.0.49">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <UseIISExpress>true</UseIISExpress>
    <IISExpressSSLPort>44304</IISExpressSSLPort>
    <IISExpressAnonymousAuthentication />
    <IISExpressWindowsAuthentication />
    <IISExpressUseClassicPipelineMode />
    <UseGlobalApplicationHostFile />
    <Use64BitIISExpress />
    <LangVersion>9.0</LangVersion>
    <AssemblyTitle>MyProject</AssemblyTitle>
  </PropertyGroup>
  <ItemGroup>
    [.. a few package references]
  </ItemGroup>
  <ItemGroup>
    [.. a few linked files to add to compilation]
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.Net.Compilers.Toolset" Version="3.11.0" />
  </ItemGroup>
</Project>
```

I'm guessing asmx and ascx files would be affected as well.

So I think the default item includes should have:

```xml
  <ItemGroup>
    <Content Include="*.asax" />
    <Content Include="*.ascx" />
    <Content Include="*.asmx" />
    <Content Include="*.aspx" />
  </ItemGroup>
```

**Comment by CZEMacLeod** [comment]
It has been a while since I did webforms development (I mainly use/maintain MVC and Razor these days).
Are there any other types that should be included? I seem to remember master pages (`.master`?).
I believe these should be recursive so they include at any depth of folder, not just the root so probably something like
```xml
  <ItemGroup>
    <Content Include="**\*.asax" />
    <Content Include="**\*.ascx" />
    <Content Include="**\*.asmx" />
    <Content Include="**\*.aspx" />
    <Content Include="**\*.master" />
  </ItemGroup>
```
I'll look at adding these as default includes, perhaps behind a flag so that they can be disabled if required.

**Comment by chucker** [comment]
Good point — `.master`, too. And yes, it should be recursive (technically, the rules are more complex; e.g. `App_Code` should not contain markup).

**Comment by klinki** [comment]
I believe `.ashx` should be also included

**Comment by chucker** [comment]
Possibly also resx, axd, config.

**Comment by CZEMacLeod** [comment]
@chucker .resx and web.config files were already handled. And .axd files do not actually exist - the URLs are just routed to a handler class by IIS.

**Comment by mcnallys** [comment]
@CZEMacLeod Thanks for the great work on this project.  I updated to this version and noticed an issue after performing a publish.

In my project I end up with "bin\Release\Publish"  as the output folder, however if turn on EnableWebFormsDefaultItems, once I publish it see's that published folder as content. Then each publish adds more content upon itself and eventually errors.

I have worked around this in some of my other globs by adding Exclude="$(DefaultItemExcludes)".

I recommend changing from:

```
<Content Include="**\*.asax" />
<Content Include="**\*.ascx" />
<Content Include="**\*.ashx" />
<Content Include="**\*.asmx" />
<Content Include="**\*.aspx" />
<Content Include="**\*.master" />
```

to

```
<Content Include="**\*.asax" Exclude="$(DefaultItemExcludes)" />
<Content Include="**\*.ascx" Exclude="$(DefaultItemExcludes)" />
<Content Include="**\*.ashx" Exclude="$(DefaultItemExcludes)" />
<Content Include="**\*.asmx" Exclude="$(DefaultItemExcludes)" />
<Content Include="**\*.aspx" Exclude="$(DefaultItemExcludes)" />
<Content Include="**\*.master" Exclude="$(DefaultItemExcludes)" />
```

**Comment by CZEMacLeod** [comment]
@mcnallys The props file actually adds all the item types to `DefaultItemExcludes` so using that to exclude won't work.
However, we can setup excludes for the `Content` entries 

```xml
  <!-- Exclude WebForms items from default items -->
  <PropertyGroup Condition="'$(EnableWebFormsDefaultItems)'=='true'">
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.asax;*.asax</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.ascx;*.ascx</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.ashx;*.ashx</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.asmx;*.asmx</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.aspx;*.aspx</DefaultItemExcludes>
    <DefaultItemExcludes>$(DefaultItemExcludes);**\*.master;*.master</DefaultItemExcludes>
    <DefaultWebFormsItemExcludes>$(BaseOutputPath)\**;$(BaseIntermediateOutputPath)\**</DefaultWebFormsItemExcludes>
  </PropertyGroup>

  <!-- Include WebForms items as content -->
  <ItemGroup Condition="'$(EnableWebFormsDefaultItems)'=='true'">
    <Content Include="**\*.asax" Exclude="$(DefaultWebFormsItemExcludes)" />
    <Content Include="**\*.ascx" Exclude="$(DefaultWebFormsItemExcludes)" />
    <Content Include="**\*.ashx" Exclude="$(DefaultWebFormsItemExcludes)" />
    <Content Include="**\*.asmx" Exclude="$(DefaultWebFormsItemExcludes)" />
    <Content Include="**\*.aspx" Exclude="$(DefaultWebFormsItemExcludes)" />
    <Content Include="**\*.master" Exclude="$(DefaultWebFormsItemExcludes)" />
  </ItemGroup>
```
If you try this (but change `EnableWebFormsDefaultItems` to `EnableWebFormsDefaultItems2`) and it resolves the issue for you, I can make the update and publish.

**Comment by CZEMacLeod** [comment]
@mcnallys I've created a new issue #25 for this problem.
