### ISSUE TITLE
AutoGenerateBindingRedirects causes output xml attributes to change order randomly

### ISSUE THREAD

**Issue by laped** [CZEMacLeod/MSBuild.SDK.SystemWeb#48]
Not sure this is the right repo to ask this, but I just changed one of our projects to use this SDK and set these properties: 

`
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
<GeneratedBindingRedirectsAction>Overwrite</GeneratedBindingRedirectsAction>
`

When building the project it occasionally makes updates to the config that looks like this:

![image](https://user-images.githubusercontent.com/1386311/213692853-16e00868-1bec-43b1-b134-f784feba0617.png)

For some reason it changes the order of those attributes in the xml, but the order seems to be random or always opposite of the current xml. Some times `publicKeyToken` comes first, other times it's the `culture` attribute. The value of the attributes doesn't change.

Does this xml output come from this project or is it coming from an msbuild task/target?

**Comment by leusbj** [comment]
As of [v4.0.77](https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/releases/tag/v4.0.77) this package has used the MSBuild engine to create/generate the potentially new content of the `web.config file`.

Under normal circumstances MSBUild is only overwriting an `<<applicationnamehere>>.config` file in the \bin directory (a transient and generated file traditionally not source controlled).  

When the `<GeneratedBindingRedirectsAction>Overwrite</GeneratedBindingRedirectsAction>` property is set, the output is redirected to the main project directory `web.config`.
