### ISSUE TITLE
"ASP.NET Core Module is required" when running in Visual Studio

### ISSUE THREAD

**Issue by Bouke** [CZEMacLeod/MSBuild.SDK.SystemWeb#51]
# Steps to reproduce
- ```
  mkdir SystemWeb
  cd SystemWeb
  dotnet new systemwebfull
  ```
- Open SystemWeb.csproj in Visual Studio Community 2022
- Start Debugging (F5)

# What happens
Visual Studio now shows this error message: "The ASP.NET Core Module is required to host ASP.NET Core projects in IIS Express and does not appear to be installed. Try repairing Visual Studio to correct the problem."

When I try to run the project in Rider, I need to disable the Core Module by removing the following from `applicationhost.config`.
```
<add name="AspNetCoreModuleV2" image="C:\Program Files\IIS\Asp.Net Core Module\V2\aspnetcorev2.dll" />
```
In Rider I can then run the project in IIS Express, but not debug it. The debug button becomes greyed out, so it's probably trying to start something or wait on something that doesn't happen.

# What should happen
How can I run/debug the project with Visual Studio, and debug it with Rider?
---
# Update
For Rider, there's a workaround [documented here](https://youtrack.jetbrains.com/issue/RIDER-66190/SDK-Style-Project-Format-for-ASP.NET-Web-Applications-.net-Framework#focus=Comments-27-5167409.0-0). Not ideal, but debugging works. I think that with Visual Studio's launch profiles one can achieve the same in Visual Studio.

**Comment by CZEMacLeod** [comment]
I have just tried this and I cannot reproduce it. Can you confirm which version of VS you have installed, and which operating system. It might also be useful to know if you have the global ANCM runtime installed. There is an issue with V17.5 of VS - but I'm not sure if this is related. I've tried V17.6.0P1.0 and V17.4.5.
There is a launch settings file included in the template.
Please ensure you have the latest templates installed.
The line in the generated file `.vs\{projectname}\config\applicationhost.config` I end up with is slightly different from yours, but I don't know why specifically.
```xml
<add name="AspNetCoreModuleV2" image="%IIS_BIN%\Asp.Net Core Module\V2\aspnetcorev2.dll" />
```
For reference I used

```cmd
dotnet new systemwebfull -n test
cd test
start .
```
Then opened test.csproj in VS2022 Pro. And the file generated was `.vs\test\config\applicationhost.config`. I don't believe that Pro vs Community edition will make any difference.
It might be that there are some components I have installed (or not installed) that might make a difference - but it seems unlikely.

If I have time, I'm going to try this on the 'developer image in a box' available at https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ - I may have to add the ASP.NET and web development workload to that - I'm not sure if that is installed by default.

**Comment by CZEMacLeod** [comment]
@Bouke I've tried this on the windows developer image mentioned above and cannot replicate the issue you are describing.
I would suggest it is something local to your computer or setup, or you have not got some visual studio element installed.
Please ensure you are using VS2022 V17.4.4 or V17.6.0P1.0 (there is an issue with 17.5.0).
Any issues with the use of this in Rider will have to be taken up with their development team.

**Comment by Bouke** [comment]
I've just updated from 17.1 to 17.6.2 and running the web project fails with the same error message:

<img width="496" alt="image" src="https://github.com/CZEMacLeod/MSBuild.SDK.SystemWeb/assets/235882/5749ddfb-079d-4991-b72e-5c83ba86041a">

**Comment by CZEMacLeod** [comment]
Do you have ANCM installed at all? It certainly isn't used when running systemweb based aspnet projects using this sdk, but maybe VS is doing an unnecessary check here.

**Comment by Meligy** [comment]
Has anyone solved this? I'm seeing it as well.

**Comment by gfody** [comment]
I'm seeing this error on Visual Studio 2022 (ARM 64bit) Preview Version 17.11.0 Preview 6.0

running iisexpress directly is working though I haven't figured out how to get it to automatically launch the browser (it seems like iisexpress should have arguments for that but I haven't been able to find them).
eg launchSettings.json:
```json
{
    "$schema": "http://json.schemastore.org/launchsettings.json",
    "profiles": {
        "Profile 1": {
            "commandName": "Executable",
            "executablePath": "C:\\Program Files\\IIS Express\\iisexpress.exe",
            "commandLineArgs": "/config:$(SolutionDir)\\.vs\\$(SolutionName)\\config\\applicationhost.config /site:$(ProjectName)"
        }
    }
}
```

**Comment by CZEMacLeod** [comment]
@gfody I'm not sure how much of this works on ARM tbh. That is not a scenario I can really test unfortunately.
I think you do need the ASPNET Core Module installed, although it doesn't (shouldn't) get added to the web.config for SystemWeb SDK projects, it is used as part of the detection for launch.

**Comment by gfody** [comment]
ah so I didn't realize that this is something that needs to be installed outside the vs installer.

after installing this:
```
winget install Microsoft.DotNet.AspNetCore.6
```

and adding this to the csproj:
```
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>
```

the default launch template with commnadName IISExpress is working.

fwiw everything seems to be working well on arm.

**Comment by gfody** [comment]
it wasn't necessary on my normal pc and I do not have the ANCM installed there. I only needed this on arm64

**Comment by jstoppa** [comment]
> I'm seeing this error on Visual Studio 2022 (ARM 64bit) Preview Version 17.11.0 Preview 6.0
> 
> running iisexpress directly is working though I haven't figured out how to get it to automatically launch the browser (it seems like iisexpress should have arguments for that but I haven't been able to find them). eg launchSettings.json:
> 
> ```json
> {
>     "$schema": "http://json.schemastore.org/launchsettings.json",
>     "profiles": {
>         "Profile 1": {
>             "commandName": "Executable",
>             "executablePath": "C:\\Program Files\\IIS Express\\iisexpress.exe",
>             "commandLineArgs": "/config:$(SolutionDir)\\.vs\\$(SolutionName)\\config\\applicationhost.config /site:$(ProjectName)"
>         }
>     }
> }
> ```

this worked for me, thanks

**Comment by duncansmart** [comment]
> running iisexpress directly is working though I haven't figured out how to get it to automatically launch the browser

I prefer the browser not launching, but you could write a batch file that launches your browser (`start http://localhost:1234`) then runs the IISExpress command line with the passed args. e..g

```
start http://localhost:1234
"C:\Program Files\IIS Express\iisexpress.exe" %*
if errorlevel 1 pause
```
