### ISSUE TITLE
IIS Express profile launchSettings.json does not add environment variables in the iisexpress.exe process

### ISSUE THREAD

**Issue by morindo** [CZEMacLeod/MSBuild.SDK.SystemWeb#65]
Our current Web app csproj is currently using the great (and thank you so much) MSBuild.SDK.SystemWeb/4.0.88 Sdk and when we launch the IIS Express profile (in debug or without debugging) from VS 2022, it does add the environment variables to the iisexpress.exe process, is this normal? Notice that it is working with a default ASP.NET Core Web App default project.

This is our launchSettings.json

```{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:51867/",
      "sslPort": 44301
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": false,
      "environmentVariables": {  // This does not work
        "ASPNETCORE_ENVIRONMENT": "Development",
        "AAA": "BBB"
      }
    }
  }
}

**Comment by morindo** [comment]
Thank you very much @CZEMacLeod for the quick response. Good hunch, I'll look into-it myself. I'll post if I find something.

**Comment by swissarmykirpan** [comment]
@morindo @CZEMacLeod any progress on this?

**Comment by morindo** [comment]
@swissarmykirpan unfortunately, I didn't find a way to make IISExpress use the launchSettings.json environment variable.

**Comment by julealgon** [comment]
Ran into this behavior today. @CZEMacLeod should this be tagged with the `known limitation` label?

Additionally, is there any known workarounds to this issue besides just forcing a system-wide environment variable?

**Comment by gfody** [comment]
as a workaround, this is working for me
```json
    "Profile 1": {
        "commandName": "Executable",
        "executablePath": "C:\\Program Files\\IIS Express\\iisexpress.exe",
        "commandLineArgs": "/config:$(SolutionDir)\\.vs\\$(ProjectName)\\config\\applicationhost.config /site:$(ProjectName)",
        "environmentVariables": {
            "AAA": "BBB",
        }
```

**Comment by julealgon** [comment]
Oh, that is _very_ interesting @gfody ! Thanks for sharing, will definitely try this to remove some of our custom runtime env checks that we added because of the lack of support for env vars locally!

**Comment by CZEMacLeod** [comment]
Just because I've been working on something that had to get the `applicationhost..config` file recently - I can tell you that the path is `$(SolutionDir)\.vs\$(SolutionName)\config\applicationhost.config`

@gfody - I assume that your use case has the same solution name as your main web project.

**Comment by gfody** [comment]
> Just because I've been working on something that had to get the `applicationhost..config` file recently - I can tell you that the path is `$(SolutionDir)\.vs\$(SolutionName)\config\applicationhost.config`
> 
> @gfody - I assume that your use case has the same solution name as your main web project.

ah that makes sense, ty!
