### ISSUE TITLE
Issue with files copied to output folder

### ISSUE THREAD

**Issue by markusbaumgartltdmsystems** [CZEMacLeod/MSBuild.SDK.SystemWeb#78]
Hi there!
I was very pleased to find a way to make use of old ASP.NET projects with the new project structure.
Unfortunately we ran into an issue with the set of files copied to the output folder.
We are missing PDB/XML from referenced packages.

In order to demonstrate I added a package reference to the sample in your code repo:

```
<Project Sdk="MSBuild.SDK.SystemWeb/4.0.88">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <Copyright>Copyright ©  2021</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\launchSettings.json" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNetZip" Version="1.16.0" />
  </ItemGroup> 
</Project>
```

I also created an old project structure style project and compared the contents of the bin folder:
![2024-08-05_13-31-39](https://github.com/user-attachments/assets/df7169ef-df60-48fc-87b5-7fab950ee62c)

For referenced projects this seems to be working.
Can you help me if I am doing somethin wrong or missing something to achieve the same output files?

**Comment by CZEMacLeod** [comment]
Interesting.

Any specific reason you need to PDB files to be local? I believe that VS will find the PDB files from the packages, or resolve them using nuget anyway...

Looks like this is related to <PackageReference> vs packages.config or CPS vs Legacy - it is covered in https://github.com/dotnet/sdk/issues/1458

If looks like if you add a global.json and set the SDK version to net 7 or higher (I would recommend net8), then you can use the following properties.

> To copy to the output directory xml/documentation files, then set `CopyDocumentationFilesFromPackages` to true.
> To copy debug symbol files to the output directory, then set `CopyDebugSymbolFilesFromPackages` to true.

**Comment by markusbaumgartltdmsystems** [comment]
Actually I am more interested in the XML in this case.
In my concrete scenario the XML from another package is needed to create a proper Swagger documentation.

I added the commands to the project file and now it works as expected.

Many thanks for your quick response!
